### ISSUE TITLE
(Bug) The web site regressed and is not functional.

### ISSUE THREAD

**Issue by sjasthi** [sjasthi/vunnava#2]
[20-Aug-2022 06:47:15 America/Boise] PHP Warning:  require_once(/home2/icsbinco/public_html/vunnava/vunnava/bin/adminFunctions.php): Failed to open stream: No such file or directory in /home2/icsbinco/public_html/vunnava/index.php on line 3
[20-Aug-2022 06:47:15 America/Boise] PHP Fatal error:  Uncaught Error: Failed opening required '/home2/icsbinco/public_html/vunnava/vunnava/bin/adminFunctions.php' (include_path='.:/opt/cpanel/ea-php80/root/usr/share/pear') in /home2/icsbinco/public_html/vunnava/index.php:3
Stack trace:
#0 {main}
  thrown in /home2/icsbinco/public_html/vunnava/index.php on line 3

**Comment by SamaraGarrett** [comment]
Still not sure what the cause of that error was, I tried removing 'vunnava' from the require_once call but then go the error:
"PHP Warning:  require_once(/home2/icsbinco/public_html/bin/adminFunctions.php): Failed to open stream: No such file or directory in /home2/icsbinco/public_html/vunnava/index.php on line 3"
So I added the 'vunnava' back into the address and it began working. Confused as to why it was broken in the first place.

After fixing that, got a new error:
"PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home2/icsbinco/public_html/vunnava/bin/Classes/PHPExcel/Shared/String.php on line 526"
So I replaced the relevant "{}" braces with "[]" braces and the front page of the website is working again. I am working my way through the code to find other instances of curly braces being used in this manner to make sure that other pages of the site won't throw this error.

Example of curly braces that needed to be replaced:
<img width="967" alt="Screen Shot 2022-10-14 at 4 45 29 PM" src="https://user-images.githubusercontent.com/25229257/195950166-36cfaf9e-b070-4b24-844b-295526305e65.png">

**Comment by SamaraGarrett** [comment]
I replaced all array and string offset access curly braces that I could find with brackets. I've uploaded the changed files to vunnava.com using FTP and created a pull request with the github changes. Please confirm that the website is working as expected and let me know if any of the pages are still not working (in case I missed some curly braces somewhere).

**Comment by sjasthi** [comment]
Thank you. It looks good!
